#!/usr/bin/env python3
"""MCC 3.0 Stage 6 — repository end-to-end/provenance audit.

This script does not create new physical outputs. It validates the results and
handoffs already generated by Stages 1–5 and writes final audit JSON.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parent
REPO=ROOT.parents[1]
OUT=ROOT/"results"; OUT.mkdir(parents=True,exist_ok=True)

def read(rel):
    return json.loads((REPO/rel).read_text())

def main():
    s1=read("mcc_3_0/stage_1_baseline_freeze/results/verification.json")
    s1m=read("mcc_3_0/stage_1_baseline_freeze/baseline_manifest.json")
    s2=read("mcc_3_0/stage_2_finite_source_insertion/results/results.json")
    s2v=read("mcc_3_0/stage_2_finite_source_insertion/results/verification.json")
    s2h=read("mcc_3_0/stage_2_finite_source_insertion/STAGE3_HANDOFF.json")
    s3=read("mcc_3_0/stage_3_particle_component_replay/results/results.json")
    s3v=read("mcc_3_0/stage_3_particle_component_replay/results/verification.json")
    s3h=read("mcc_3_0/stage_3_particle_component_replay/STAGE4_HANDOFF.json")
    s4=read("mcc_3_0/stage_4_single_load_energy_master_ledger/results/results.json")
    s4v=read("mcc_3_0/stage_4_single_load_energy_master_ledger/results/verification.json")
    s4h=read("mcc_3_0/stage_4_single_load_energy_master_ledger/STAGE5_HANDOFF.json")
    s5=read("mcc_3_0/stage_5_macro_universe_replay/results/results.json")
    s5v=read("mcc_3_0/stage_5_macro_universe_replay/results/verification.json")
    s5h=read("mcc_3_0/stage_5_macro_universe_replay/STAGE6_HANDOFF.json")

    checks={}
    checks["stage2_to_stage3_NU"]=s2["stage3_handoff"]["N_U"]==s2h["source_state"]["N_U"]==s3["inputs"]["stage2"]["N_U"]
    checks["stage2_to_stage3_calibration"]=(
        s2["stage3_handoff"]["alpha"]==s2h["source_state"]["alpha"] and
        s2["stage3_handoff"]["threshold_h"]==s2h["source_state"]["threshold_h"] and
        s2["stage3_handoff"]["derived_effective_beta"]==s2h["source_state"]["derived_effective_beta"])
    checks["stage3_to_stage4_state"]=(
        s3h["source_state"]["N_U"]==s4["inputs"]["N_U"] and
        abs(s3h["source_state"]["phenotype_weight"]-s4["inputs"]["arithmetic_shares"]["phenotype"])<1e-12)
    sumE=sum(x["energy_J"] for x in s4["additive_master_ledger"])
    checks["stage4_master_energy_closure"]=abs(sumE-s4["totals"]["total_energy_J"])<1e-24
    present=s5["uniform_macro_replay"][1]
    checks["stage4_to_stage5_total_pressure"]=(
        abs(s4h["source_state"]["total_energy_J"]-present["total_density_J_m3"])<1e-24 and
        abs(s4h["source_state"]["total_pressure_Pa"]-present["total_pressure_Pa"])<1e-24)
    checks["stage4_to_stage5_q"]=abs(s4h["source_state"]["diagnostic_q"]-present["deceleration_q"])<1e-15
    checks["stage5_to_stage6_macro_handoff"]=(
        abs(s5h["source_state"]["present_q"]-present["deceleration_q"])<1e-15 and
        abs(s5h["source_state"]["present_rotation_km_s"]-present["rotation_km_s"])<1e-12 and
        abs(s5h["source_state"]["present_lensing_arcsec"]-present["lensing_arcsec"])<1e-15)
    checks["all_stage_verification_passed"]=all([
        s1["all_checks_passed"],s2v["all_checks_passed"],s3v["all_checks_passed"],
        s4v["all_checks_passed"],s5v["all_checks_passed"]])
    checks["no_stage4_stage5_SI_refit"]=(
        s4["inputs"]["energy_coefficient_refit"] is False and
        s5["inputs"]["refit"] is False and
        s5h["source_state"]["coefficients_refit"] is False)
    checks["no_component_energy_double_count"]=(
        s4["typed_ledger_policy"]["double_count_forbidden"] is True and
        s5["checks"]["stage4_internal_views_not_added"] is True)
    checks["conditional_claims_remain_open"]=(
        any("N_U = L*H*C" in x for x in s1m["open_assumptions"]) and
        s3["spin"]["status"]=="OPEN" and
        s3["particle_candidate"]["species_decoder_unique"] is False)

    stage_counts={
      "stage1":len(s1["checks"]),
      "stage2":len(s2v["checks"]),
      "stage3":len(s3v["checks"]),
      "stage4":len(s4v["checks"]),
      "stage5":len(s5v["checks"])
    }

    audit={
      "project":"Minimal Computing Cosmology 3.0",
      "stage":"6_end_to_end_closure",
      "date":"2026-10-07",
      "stage_status":"PASS" if all(checks.values()) else "FAIL",
      "integrated_model_status":"PASS-C" if all(checks.values()) else "FAIL",
      "stage_check_counts":stage_counts,
      "published_stage_checks_total":sum(stage_counts.values()),
      "cross_stage_checks":[
        {"id":f"S6-{i+1:02d}","check":k,"passed":bool(v)}
        for i,(k,v) in enumerate(checks.items())
      ],
      "cross_stage_checks_total":len(checks),
      "grand_declared_checks_total":sum(stage_counts.values())+len(checks),
      "all_checks_passed":all(checks.values()),
      "final_outputs":{
        "N_U":s2h["source_state"]["N_U"],
        "alpha":s2h["source_state"]["alpha"],
        "threshold_h":s2h["source_state"]["threshold_h"],
        "derived_effective_beta":s2h["source_state"]["derived_effective_beta"],
        "phenotype_share":s4["inputs"]["arithmetic_shares"]["phenotype"],
        "resident_nonphenotype_share":s4["inputs"]["arithmetic_shares"]["resident_nonphenotype"],
        "return_share":s4["inputs"]["arithmetic_shares"]["return"],
        "present_total_energy_J":s4["totals"]["total_energy_J"],
        "present_pressure_Pa":s4["totals"]["total_pressure_Pa"],
        "present_q":present["deceleration_q"],
        "present_aT_m_s2":present["aT_m_s2"],
        "present_rotation_km_s":present["rotation_km_s"],
        "present_lensing_arcsec":present["lensing_arcsec"],
        "acceleration_transition_scale_factor":s5["acceleration_transition_scale_factor"]
      },
      "open_claims":{
        "finite_source":s1m["open_assumptions"],
        "particle_species_unique":s3["particle_candidate"]["species_decoder_unique"],
        "spin":s3["spin"],
        "binding_and_covariant_completion":"OPEN"
      },
      "interpretation":"PASS closes the six-stage computational/provenance integration. PASS-C is retained for the integrated scientific model because finite-SOURCE uniqueness and parts of microscopic particle interpretation remain conditional."
    }
    (OUT/"end_to_end_audit.json").write_text(json.dumps(audit,indent=2,ensure_ascii=False,allow_nan=False)+"\n")
    verification={
      "project":audit["project"],"stage":audit["stage"],"date":audit["date"],
      "verdict":audit["stage_status"],
      "integrated_model_status":audit["integrated_model_status"],
      "checks":audit["cross_stage_checks"],
      "published_stage_checks_total":audit["published_stage_checks_total"],
      "cross_stage_checks_total":audit["cross_stage_checks_total"],
      "grand_declared_checks_total":audit["grand_declared_checks_total"],
      "all_checks_passed":audit["all_checks_passed"]
    }
    (OUT/"verification.json").write_text(json.dumps(verification,indent=2,ensure_ascii=False)+"\n")
    assert audit["all_checks_passed"],checks
    print(json.dumps({
      "stage6":audit["stage_status"],
      "MCC_3_0":audit["integrated_model_status"],
      "stage_checks":audit["published_stage_checks_total"],
      "cross_stage_checks":audit["cross_stage_checks_total"],
      "total_checks":audit["grand_declared_checks_total"],
      "N_U":audit["final_outputs"]["N_U"],
      "q0":audit["final_outputs"]["present_q"],
      "rotation_km_s":audit["final_outputs"]["present_rotation_km_s"],
      "lensing_arcsec":audit["final_outputs"]["present_lensing_arcsec"]
    },indent=2))

if __name__=="__main__": main()
