from pathlib import Path
import json,os
from xml.sax.saxutils import escape
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Table,TableStyle,PageBreak,KeepTogether
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
R=Path(__file__).resolve().parent
pdfmetrics.registerFont(TTFont('Nanum',os.environ.get('WRRA_FONT_PATH','/usr/local/share/fonts/wrra/NanumGothic.ttf')))
r=json.loads((R/'results.json').read_text());W=A4[0]-88
styles={'body':ParagraphStyle('body',fontName='Nanum',fontSize=9.5,leading=14,spaceAfter=8,wordWrap='CJK'),
 'title':ParagraphStyle('title',fontName='Nanum',fontSize=20,leading=27,spaceAfter=10),
 'sub':ParagraphStyle('sub',fontName='Nanum',fontSize=13,leading=19,spaceAfter=10),
 'head':ParagraphStyle('head',fontName='Nanum',fontSize=12,leading=18,spaceBefore=10,spaceAfter=8,keepWithNext=True),
 'cell':ParagraphStyle('cell',fontName='Nanum',fontSize=8.2,leading=12,wordWrap='CJK'),
 'small':ParagraphStyle('small',fontName='Nanum',fontSize=8.5,leading=12,spaceAfter=6,wordWrap='CJK')}
def p(t,style='body'):return Paragraph(escape(t).replace('\n','<br/>'),styles[style])
def table(rows,ratios):
 t=Table([[p(str(x),'cell') for x in row] for row in rows],colWidths=[W*x/sum(ratios) for x in ratios],repeatRows=1,hAlign='LEFT')
 t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),colors.HexColor('#E7EEF5')),('VALIGN',(0,0),(-1,-1),'TOP'),('GRID',(0,0),(-1,-1),.35,colors.HexColor('#B9C5D1')),('LEFTPADDING',(0,0),(-1,-1),7),('RIGHTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),7),('BOTTOMPADDING',(0,0),(-1,-1),7)]));return t
def footer(c,d):
 c.setFont('Nanum',8);c.setFillColor(colors.HexColor('#536276'));c.drawString(44,26,'WRRA M | bridge 0.5-0.8 r1 | reviewed collection | 2026-10-03');c.drawRightString(A4[0]-44,26,str(d.page))
def build(lang):
 ko=lang=='KO';story=[];transcript=[]
 def add(t,style='body'):story.append(p(t,style));transcript.append(t)
 def tab(rows,ratios):story.append(table(rows,ratios));story.append(Spacer(1,10));transcript.extend(' | '.join(map(str,row)) for row in rows)
 def page():story.append(PageBreak());transcript.append('\n')
 add('WRRA M 상하류 연결 연구 0.5-0.8 r1' if ko else 'WRRA M Bridge Research 0.5-0.8 r1','title')
 add('시계·측정·되먹임·최종 일관성 재검토' if ko else 'Reviewed Clock, Measurement and Feedback Collection','sub')
 add('최원식 · 최정인 / Wonsik Choi · Jeongin Choi\n2026-10-03 · CC BY 4.0','small')
 add('1. 평가와 실행 범위' if ko else '1. Evaluation and executed scope','head')
 tab(([['평가 단계','이번 검토의 근거'],['검증·고정 입력','SI 변환, 하류 전자 에너지·모드, 상류 유한 주소·내부 H, 검토 r1의 보정 장부. 구성 가정인 인구·종·저장고·시계·공간 계수는 별도 표시한다.'],['WRRA 변환','주소 조건부 상태 → 같은 내부 H → 중복 없는 SI 장부 → 균질 압력·팽창. 같은 고유시간의 측정·기록, 별도 유효 공간 되먹임을 실행한다.'],['산출값','7단계 재실행; 단계 검사 1,116개 + 검토 검사 188개 = 1,304개 통과. 깨끗한 폴더의 8개 결과 JSON이 바이트 단위로 동일하다.'],['반증조건','정규화·양성성·에너지·압력·시간 위상·전류·수렴·입력 의존성이 명세와 불일치하면 해당 연결을 기각한다. 공변 통합은 실행 코드가 없으므로 미완료로 유지한다.']] if ko else [['Evaluation','Evidence in this review'],['Verified/frozen inputs','SI conversion, downstream electron energy/mode, finite upstream address state/internal H and reviewed r1 ledger. Population, species, reservoir, clock and spatial coefficients remain disclosed construction inputs.'],['WRRA transformation','Address-conditioned state -> same internal H -> nonduplicated SI ledger -> homogeneous pressure/expansion; adopted proper-time measurement/record and a separate effective spatial feedback path.'],['Outputs','Seven stages replayed: 1,116 stage checks + 188 review checks = 1,304 passed. Eight result JSON files are byte-identical in a clean directory.'],['Falsification','Reject an adapter if trace, positivity, energy, pressure, phase, current, convergence or input dependence contradicts its specification. A full covariant bridge remains open because its joint dynamics is not implemented.']]),[1,4])
 add('단계별 검사 수' if ko else 'Stage check counts','head')
 namesKO=['형식·범위 계약','주소 조건부 CQ 상태','SI 교환·중복 방지','균질 압력·FRW','조건부 SI 시계·위상','측정·기록·반복','유효 비균질 되먹임'];namesEN=['Typed scope contract','Address-conditioned CQ state','SI exchange without duplication','Homogeneous pressure/FRW','Conditional SI clock/phase','Measurement/record/repetition','Effective nonuniform feedback']
 tab([['단계' if ko else 'Stage','실행' if ko else 'Execution','통과' if ko else 'Passed']]+[[x['stage'],(namesKO if ko else namesEN)[i],x['passed']] for i,x in enumerate(r['stages'])],[.6,3.5,.6])
 add('검사 수에는 수학·구현·입력 해시 검사와 알려진 한계를 확인하는 검사가 포함된다. 실험 횟수나 독립적인 관측 검증 수로 해석하지 않는다.' if ko else 'Counts include mathematical/implementation checks, provenance and confirmation of expected limitations. They are not numbers of independent experiments or observational confirmations.','small')
 page()
 add('2. 실제 연결과 보관된 근거' if ko else '2. Executed connections and retained provenance','head')
 rowsKO=[['연결','판정','전달 내용 / 한계'],['0.2 → 0.3 → 0.4','실행','여기 에너지 → 외부 보정 인구의 SI 부하 → 같은 E(V)의 압력·FRW. 실제 입자 생성·준비 시간 법칙은 미포함.'],['0.2 + 0.5 → 0.6','실행','같은 내부 에너지 차와 선택한 프레임 → 관측 후 상태·반복 전환. 자율 장치·리셋 비용은 미포함.'],['0.2 → 0.7','실행','기준 인구 → 선택한 공간 분포 → 점유 밀도 → 장 → 상태. 무차원 비상대론적 유효 모형.'],['0.5 → 0.7','근거 보관','시계 결과는 해시·해석 근거다. 시계율을 바꿔도 장 계산은 변하지 않는다. SI 길이·운동항·G 보정 미완료.'],['0.6 → 0.7','근거 보관','측정 결과는 보관하지만 관측 후 상태·장치·기록 에너지를 장 진화에 되먹이지 않는다.'],['0.6 → 0.3/0.4','검토 진단','0.8에서 1회 측정 평균 비용을 기존 SI 장부에 삽입하고 외부/포함 공급원 경계를 검사했다. 실제 시간·공간 장치는 미포함.']]
 rowsEN=[['Connection','Status','Payload / limit'],['0.2 -> 0.3 -> 0.4','Executed','Excitation -> externally matched SI population load -> pressure/FRW from one E(V). Particle creation and preparation time law remain open.'],['0.2 + 0.5 -> 0.6','Executed','Same internal gap and adopted frame -> post-observation states/repeated transitions. Autonomous apparatus/reset remain open.'],['0.2 -> 0.7','Executed','Baseline populations -> chosen spatial profiles -> occupancy -> field -> state. Dimensionless nonrelativistic effective model.'],['0.5 -> 0.7','Provenance','Clock snapshot is retained. Changing its rate leaves field results unchanged. SI length/kinetic/G calibration remains open.'],['0.6 -> 0.7','Provenance','Measurement snapshot is retained; post-measurement state/apparatus/record energy is not fed into field evolution.'],['0.6 -> 0.3/0.4','Review diagnostic','0.8 inserts one mean write cost into the existing SI ledger and checks external/included supply boundaries. Actual apparatus space-time dynamics remains open.']]
 tab(rowsKO if ko else rowsEN,[1.2,.9,3.4])
 add('입력 교란에 대한 실행 확인' if ko else 'Behavioral input-dependency probes','head')
 tab(([['독립 폴더의 변경','수치 결과'],['0.7 시계율 2배','밀도·장·수렴 결과 동일; 최대 밀도 차 0'],['0.7 측정 work 2배','밀도·장·수렴 결과 동일; 최대 밀도 차 0'],['0.7 기준 인구를 0.12로 변경','최대 최종 밀도 차 0.01681125416'],['0.6 프레임 길이 2배','첫 반복 전환 행렬 최대 차 0.55243420946']] if ko else [['Isolated input change','Numerical response'],['Double 0.7 clock rate','Density/field/convergence unchanged; maximum density difference 0'],['Double 0.7 measurement work','Density/field/convergence unchanged; maximum density difference 0'],['Set 0.7 baseline population to 0.12','Maximum final density difference 0.01681125416'],['Double 0.6 frame duration','First repeated-transition matrix maximum difference 0.55243420946']]),[2,3])
 add('교란은 해당 코드가 입력을 실제 사용하는지 확인하는 합성 검사다. 인구 변경은 상류 상태의 재보정이나 물리적 입자 생성 계산으로 세지 않는다.' if ko else 'These synthetic perturbations test actual code dependencies. The population perturbation is not counted as a recalibrated upstream state or a particle-creation calculation.','small')
 add('0.7 시간 수렴 비는 4.000041, 64/128 격자 밀도 L2 차는 9.02348e-12다. 매끄러운 지정 초기 조건·유한 구간의 수렴 성과이며, 모든 조건의 정확도 증명은 아니다.' if ko else 'The 0.7 time-refinement ratio is 4.000041; the 64/128 grid density L2 difference is 9.02348e-12. This establishes convergence for the declared smooth finite test, not universal accuracy.')
 page()
 add('3. 측정 비용을 포함한 SI 장부 검사' if ko else '3. SI ledger check with measurement cost','head')
 add('검증·고정 입력: 0.2 기준 여기 인구 p=0.07997665450, 같은 H의 에너지 차 Delta, 0.5 프레임과 0.6 기록 갭, 0.3의 고정 기대 인구 Nbar와 저장고. 모두 기존 입력·실행 결과이며, 저장고 0.2 Ephi는 진단용 구성 입력이다.' if ko else 'Verified/frozen inputs: baseline excited population p=0.07997665450, the same-H gap Delta, 0.5 frame/0.6 record gap, and 0.3 fixed expected population Nbar/reservoir. The reservoir choice 0.2 Ephi is a diagnostic construction input.')
 add('WRRA 변환: 선택한 X 기저 측정은 비선택 내부 상태를 I/2로 바꾼다. 1회 평균 공급은 W=(1/2-p) Delta_J + record_gap_J/2다. 내부 여기 증가와 기록 에너지를 각각 한 번만 계상한다. 총 공급량은 Nbar W, 저장고 변화는 -Nbar W다.' if ko else 'WRRA transformation: the chosen X readout changes the nonselective internal state to I/2. Mean one-write supply is W=(1/2-p) Delta_J + record_gap_J/2. Internal excitation and record energy are each counted once. Total supply is Nbar W, opposed by reservoir change -Nbar W.')
 add('산출값: 상속 보정·양성자·기준 부피 1 m3에서 여기 증가 7.0374395222e-12 J, 기록 증가 4.3176187869e-16 J, 공급 합 7.0378712840e-12 J다. 저장고는 7.5615824991e-12 J에서 5.2371121503e-13 J로 줄어 양수를 유지한다.' if ko else 'Outputs: inherited/proton calibration at reference 1 m3 gives excitation increase 7.0374395222e-12 J, record increase 4.3176187869e-16 J and total supply 7.0378712840e-12 J. Reservoir energy falls from 7.5615824991e-12 J to positive 5.2371121503e-13 J.')
 tab(([['보정·종','공급 / J','외부 q: 전 → 후','공급원 포함 q']] if ko else [['Calibration/species','Supply / J','External q: before -> after','Included q']])+[[x['calibration']+'/'+x['species'],f"{x['controller_supply_J']:.7e}",f"{x['external_q_before']:.6f} → {x['external_q_after']:.6f}" if ko else f"{x['external_q_before']:.6f} -> {x['external_q_after']:.6f}",f"{x['included_pressureless_q']:.6f}"] for x in r['ideal_readout_boundary_diagnostics']],[1.5,1.25,1.8,1.1])
 add('외부 경계: 공급원을 제외한 계는 받은 에너지만큼 부하가 증가한다. 공급원 포함 경계: 공급원의 압력을 0으로 두는 기존 가정 아래 총에너지와 q는 재분배 전후 같다. 두 경계는 기준 총에너지부터 다르므로 서로 다른 q가 모순이 아니다.' if ko else 'External boundary: the subsystem excluding its supplier gains the supplied energy. Included boundary: with the existing pressureless-supplier assumption, total energy and q are unchanged by redistribution. The two boundaries have different reference total energy, so their distinct q values are consistent.')
 add('반증조건: 내부 증가+기록 증가가 공급량과 다르거나, 저장고가 음수가 되거나, 포함 계 총에너지가 변하거나, 같은 E(V)에서 나온 압력이 달라지면 이 삽입 장부를 기각한다. 이번 네 조합은 모두 통과했다.' if ko else 'Falsification: reject this ledger insertion if internal plus record increase differs from supply, the reservoir turns negative, included total energy changes, or pressure disagrees with the same E(V). All four declared combinations pass.')
 add('범위: 기대 인구의 평균 장부를 1회 쓴 뒤 고정 comoving 에너지 법칙을 적용한 조건부 진단이다. Q(t), 실제 장치 분포, 기록 리셋, 10만 회 물리 메모리 비용, 비균질 공변 중력을 구현한 것으로 표시하지 않는다.' if ko else 'Scope: a conditional one-write mean ledger followed by the fixed-comoving-energy rule. It does not implement Q(t), actual apparatus distribution, record reset, 100,000 physical memory costs or nonuniform covariant gravity.')
 page()
 add('4. 모순 여부와 해결 방식' if ko else '4. Consistency and resolution of apparent conflicts','head')
 tab(([['겉보기 충돌','판정·해결'],['31.8% 대 100%','resident Actual은 잔존 phi+D이고 전체 장부는 반환까지 포함한다. 범위 형식으로 구분한다.'],['5/26.8/68.2 대 4.93/26.5/68.57','주소 확률과 SI 에너지 비율은 다른 입력 형식이다. 한쪽을 자동으로 에너지에 대입하지 않고 지정 보정만 사용한다.'],['q=-0.52855 대 -0.523','각 SI 에너지 보정에서 같은 압력 법칙을 적용하면 각각 재현된다. 보정과 계 경계를 항상 같이 기록한다.'],['측정 뒤 p=0.5 대 0.4의 고정 준비 상태','측정 중에는 상태가 바뀌고 공급 work가 필요하다. 측정 이후 E(V)에 새 부하를 넣을 수 있으나 Q(t)는 열린 항목이다.'],['0.7 균일 phi=0 대 FRW 팽창','주기 Poisson은 평균을 빼므로 배경 zero mode를 계산하지 않는다. 균일 시험을 FRW 재현으로 읽지 않고, 공통 배경·섭동 adapter를 미완료로 남긴다.'],['SI 시계·기록을 보관했으니 장과 통합?','입력 교란 결과는 0.7에서 두 파일이 수치 의존성이 아님을 보여준다. 실제 연결된 것만 통합 성과로 표시한다.']] if ko else [['Apparent conflict','Assessment / resolution'],['31.8% versus 100%','Resident Actual is retained phi+D; the complete ledger includes returns. Separate them through typed scope.'],['5/26.8/68.2 versus 4.93/26.5/68.57','Address probabilities and SI energy fractions are different input types. Use a named energy calibration rather than automatic substitution.'],['q=-0.52855 versus -0.523','The same pressure law reproduces each stated energy calibration. Always retain calibration and subsystem boundary.'],['Post-readout p=0.5 versus fixed prepared state in 0.4','Readout changes the state and requires work. A post-write E(V) can use the new load; Q(t) remains open.'],['Uniform phi=0 in 0.7 versus FRW expansion','Periodic Poisson subtracts the mean and does not calculate the background zero mode. Do not count the uniform test as FRW reproduction; a common background/perturbation adapter remains open.'],['Clock/record snapshots imply field integration?','Perturbation confirms these files are not numerical dependencies of 0.7. Claim integration only for executed connections.']]),[1.7,3.3])
 add('재현·설명·예측 판정' if ko else 'Reproduction, explanation and prediction','head')
 add('기존 값을 WRRA 내부 변환으로 재현한 것은 현실 정합성과 설명 성과다. 알려진 값이라는 이유로 성과를 제외하지 않는다. 이 연구의 구조적 성과는 주소 조건부 상태, 내부 H, SI 교환, 압력과 관측·기록 비용을 같은 형식의 장부로 연결하고 경계별 결과를 실제 계산한 데 있다.' if ko else 'Reproducing known values through WRRA transformations is a consistency and explanatory achievement. The structural contribution is the executed connection of address-conditioned state, internal H, signed SI exchange, pressure and observation/record costs through typed ledgers and explicit boundaries.')
 add('검증 입력과 구성 선택을 고정한 뒤의 반복 전환 확률, 잡음별 기록 오류율, 공간 밀도·장·유한 진화는 조건부 WRRA 모형 예측이다. 예를 들어 p_flip=0.001, 256 tick에서 오류 확률은 0.2005056913이다. 실제 매체·잡음과 다른 조건으로 관측한 결과는 이 수치를 곧바로 시험하지 않는다. 같은 조건의 관측과 불일치하면 해당 모형 규칙을 수정하거나 기각한다.' if ko else 'After verified inputs and construction choices are fixed, repeated-transition probabilities, noise-conditioned record errors and finite spatial density/field evolution are conditional WRRA model predictions. At p_flip=0.001 and 256 ticks the predicted error is 0.2005056913. Observations must match the declared medium/noise conditions; a disagreement under matched conditions requires revising or rejecting that model rule.')
 page()
 add('5. 최초 10개 연결 문제의 최종 상태' if ko else '5. Final status of the ten original bridge issues','head')
 issuesKO=[['B01','범위 구분 완료'],['B02','주소·에너지 형식 구분 및 조건부 보정 완료; 인구 기원 열림'],['B03','보정·계 경계별 q 재현 완료'],['B04','대각 주소 CQ 상관·관측량별 축약 실행; 일반 얽힘 미주장'],['B05','중복 방지·유한 signed 공급 실행; 실제 준비·생성 장치 열림'],['B06','옛 시계 동일시는 실패 유지; 선택한 SI adapter 실행, 실제율 열림'],['B07','이상 측정·work·기록 잡음 실행; 물리적 내구성·리셋 열림'],['B08','내부 95차원·운반자 128차원·채널 공간 분리; 운반자 동역학 열림'],['B09','유효 비균질 되먹임 실행; 전체 SI 공변 연결 열림'],['B10','소스 이력별 상관 검사 실행; 실제 종 인구·경계는 구성 입력']]
 issuesEN=[['B01','Scope distinction resolved'],['B02','Address/energy types and conditional calibration resolved; abundance origin open'],['B03','q reproduced for each stated calibration/boundary'],['B04','Diagonal-address CQ correlation and observable reduction executed; no general entanglement claim'],['B05','Nonduplication and signed finite supply executed; physical preparation/creation apparatus open'],['B06','Old clock equality remains failed; selected SI adapter executes, physical rate open'],['B07','Ideal instrument/work/record noise executed; physical durability/reset open'],['B08','Internal 95D, carrier 128D and channel spaces separated; carrier dynamics open'],['B09','Effective nonuniform feedback executes; full SI covariant bridge open'],['B10','Source-history correlations tested; actual species population/boundary are construction inputs']]
 tab([['문제' if ko else 'Issue','최종 상태' if ko else 'Final status']]+(issuesKO if ko else issuesEN),[.55,4.45])
 add('6. 최종 판정·재현·1.0 이관' if ko else '6. Verdict, replay and handoff to 1.0','head')
 add('연결 연구의 개발 단계는 약속한 0.8에서 종료한다. 0.1–0.7의 유한 조건부 실행 성과는 보존하고, 완전한 자율·공변 연결은 열린 항목으로 남긴다. 상류 0.10·하류 0.12 마감은 변경하지 않는다. 1.0은 이 검증 범위의 통합 논문·공개 확정판이며 미완료 항목의 삭제가 아니다. 수정은 r1/r2로 처리하고 자동으로 새 개발 단계는 만들지 않는다.' if ko else 'Bridge development closes at the agreed 0.8. Preserve the finite conditional achievements of 0.1-0.7 and retain autonomous/covariant interfaces as open. Upstream closure at 0.10 and downstream at 0.12 remain unchanged. Version 1.0 consolidates this reviewed scope for publication; it does not erase open issues. Corrections use r1/r2 without automatic extra stages.')
 add('재현: numpy, scipy 설치 후 OPENBLAS_NUM_THREADS=1 python reproduce_all.py. 새 0.2 상태·기저를 0.3/0.5/0.6/0.7로, 새 0.3 장부를 0.4로, 새 0.5 시계를 0.6으로 순서대로 전달한다. 0.7 시계·기록 사본은 근거 보관으로 명시한다. 결과 8개 JSON의 바이트 동일성과 입력 해시를 확인했다. 수치 환경은 environment.json, 전체 근거는 results.json·clean_replay.json에 기록했다.' if ko else 'Replay: install numpy/scipy and run OPENBLAS_NUM_THREADS=1 python reproduce_all.py. Forward freshly generated state/basis and results in dependency order. Mark 0.7 clock/measurement copies as provenance. Eight result JSON files are byte-identical; input hashes are checked. See environment.json, results.json and clean_replay.json.')
 add('선행 공개 자료 / Prior public sources:\nBridge 0.1-0.4 r1: doi.org/10.5281/zenodo.23119802\nUpstream 1.0-r1: doi.org/10.5281/zenodo.23119041\nDownstream 0.10-0.12: doi.org/10.5281/zenodo.23113101\nGitHub: github.com/Wonsik-Choi-janefather/wrra-m-0.1','small')
 add('이 검토판 DOI: 10.5281/zenodo.23120693. 공개 경로: bridge/review_0_5_0_8_r1. 학술지 투고·수락을 주장하지 않는다.' if ko else 'Reviewed release DOI: 10.5281/zenodo.23120693. Repository directory: bridge/review_0_5_0_8_r1. No journal submission or acceptance is claimed.','small')
 page()
 add('7. r1 수정 내역과 공개 명세' if ko else '7. Revision r1 and release specification','head')
 tab(([['단계','수정','검사 수: 이전 → r1'],['0.5','작은 SI 생성자 Hermitian 검사를 상대 norm으로 변경. 전자 모드 보정과 SI 에너지 규모를 직접 비교.','133 → 134'],['0.6','원래 95차원 H의 Hermitian성, 두 모드 불변성, 투영한 상대 생성자와 초기 여기 에너지를 직접 검사.','83 → 87'],['0.7','FFT 운동 연산자의 Hermitian성과 gradient 에너지 일치, 밀도와 동적 에너지 오차의 2차 수렴을 검사. 격자 연속식의 drho가 셀 질량 미분임을 명시.','40 → 51'],['0.8','원본 ZIP에서 7단계 수치 payload를 직접 비교. 최초 10개 문제와 B09 열린 범위를 검사. 새 결과를 의존 순서대로 전달하고 현재 검토 기준을 동결.','179 → 188']] if ko else [['Stage','Revision','Checks: original -> r1'],['0.5','Use a relative norm for the small SI generator Hermitian test; directly compare electron-mode calibration and SI energy scale.','133 -> 134'],['0.6','Verify the full 95D H Hermiticity, invariant two-mode support, projected relative generator and initial excitation energy.','83 -> 87'],['0.7','Check FFT kinetic Hermiticity, matrix/gradient energy equivalence and quantitative second-order density/energy refinement. Define drho as the discrete cell-mass derivative.','40 -> 51'],['0.8','Read original ZIP result payloads and compare all seven stages; verify ten issues/B09 open scope; propagate current outputs and freeze reviewed references.','179 -> 188']]),[.5,3.9,1.2])
 add('수정 전후의 과학적 수치 payload는 모두 동일하다. version·검사·입력 해시는 의도적으로 갱신했다. 원본 0.5–0.8 ZIP은 historical/에 보존했다. 0.1–0.4 검토 r1 코드는 변경하지 않고 의존 자료로 포함한다.' if ko else 'All scientific numerical payloads remain identical. Version/check/dependency metadata is intentionally updated. Original 0.5-0.8 ZIPs are retained in historical/. Reviewed 0.1-0.4 code is unchanged and bundled as a dependency.')
 add('전체 통과 수는 1,116 단계 검사 + 188 검토 검사 = 1,304다. 원래 1,279개보다 25개 증가했다. 수정한 0.5–0.7 단계만의 검사는 272개이고, 앞 단계의 844개는 재현 기반 검사다. 188개 검토에는 이전 36개 교차 검사를 한 번만 포함한다.' if ko else 'The complete run passes 1,116 stage checks + 188 review checks = 1,304, an increase of 25 over the original 1,279. Revised 0.5-0.7 stages contribute 272 checks; prior stages contribute 844 dependency checks. The 188 review checks include the prior 36 cross-stage checks once.')
 add('공개 파일은 한·영 PDF와 전체 재현 ZIP이다. ZIP에는 수정 코드, 선언 입력, 결과, 검토 전후 비교, 최종 문제 장부, 수치 환경과 SHA256SUMS를 포함한다. 정해진 가정 아래의 재현·설명·조건부 예측 성과를 유지하며, 실제 자율 장치·전체 SI 공변 통합은 열린 항목으로 유지한다.' if ko else 'Release files are Korean/English PDFs and the complete reproduction ZIP. The ZIP includes revised code, declared inputs, results, before/after comparison, final issue register, environment and SHA256SUMS. Preserve reproduction/explanation/conditional prediction under stated assumptions and retain autonomous apparatus/full SI covariance as open.')
 add('DOI: https://doi.org/10.5281/zenodo.23120693\nGitHub: https://github.com/Wonsik-Choi-janefather/wrra-m-0.1/tree/main/bridge/review_0_5_0_8_r1','small')
 pdf=R/f'WRRA_M_Bridge_0_5_0_8_Reviewed_r1_{lang}_2026_10_03.pdf'
 SimpleDocTemplate(str(pdf),pagesize=A4,leftMargin=44,rightMargin=44,topMargin=40,bottomMargin=48,title='WRRA M Bridge 0.5-0.8 Reviewed r1',author='Wonsik Choi; Jeongin Choi').build(story,onFirstPage=footer,onLaterPages=footer)
 (R/f'WRRA_M_Bridge_0_5_0_8_Reviewed_r1_{lang}.txt').write_text('\n\n'.join(transcript))
for lang in ['KO','EN']:build(lang)
