"""Classical address / correlated carrier joint state to positive physical load."""
from pathlib import Path
import ast,json,math,hashlib
import numpy as np
from scipy.sparse import csr_matrix
ROOT=Path(__file__).resolve().parent
if not __debug__:raise RuntimeError('Run without -O')
dep=ROOT/'step4_dependency'
manifest=json.loads((dep/'RELEASE_MANIFEST.json').read_text())
for name,h in manifest['sha256'].items():assert hashlib.sha256((dep/name).read_bytes()).hexdigest()==h
D=ROOT/'step4_dependency/step3_dependency/step2_dependency';p=D/'address_structure.py';nodes=[]
for node in ast.parse(p.read_text()).body:
 if isinstance(node,ast.FunctionDef) and node.name=='product':break
 nodes.append(node)
s={'__file__':str(p),'__name__':'setup'};exec(compile(ast.Module(body=nodes,type_ignores=[]),str(p),'exec'),s)
p=D/'connection_sources/carrier_compute.py';cl=next(x for x in ast.parse(p.read_text()).body if isinstance(x,ast.ClassDef) and x.name=='Carrier');c={'np':np,'math':math,'csr_matrix':csr_matrix};exec(compile(ast.Module(body=[cl],type_ignores=[]),str(p),'exec'),c)
N=s['params']['upstream_0_9']['baseline_0_8']['ledger_0_7']['carrier_and_background']['lattice_N'];e=s['effect'];w=s['base']['w'];g=s['g'];mask=s['base']['n']%3==0
# Positive sector address measures are preserved; conditional carrier blocks
# can depend on address group. No product-of-marginals assumption is imposed.
B=np.array([[(e[j]*g[j]*w)[mask].sum(),(e[j]*g[j]*w)[~mask].sum()] for j in range(3)])
eta=np.array([s['adapter']['calibration']['eta_J_m3'][j] for j in s['ns']['SECTORS']]);V0=s['params']['reference_volume_m3'];exponents=np.array([0.,0.,3.]);checks={};rows=[]
for eps in (0.,8.):
 car=c['Carrier'](N,eps);ops=[np.eye(N),car.Kc/2,car.Kb/2];uniform=np.eye(N)/N;v=car.packet([8,16,24],[1/3]*3);packet=np.outer(v,v.conj())
 for kind,rhos in [('product',[uniform,uniform]),('correlated',[packet,uniform])]:
  sector_states=[sum(B[j,k]*rhos[k] for k in range(2)) for j in range(3)]
  assert all(np.linalg.eigvalsh(x).min()>-1e-12 for x in sector_states)
  L=np.array([np.trace(x@op).real for x,op in zip(sector_states,ops)])
  assert np.min(L)>-1e-12
  if kind=='product':assert np.allclose(L,s['mu'],atol=1e-12,rtol=0)
  group_prob=np.array([w[mask].sum(),w[~mask].sum()]);marginal=sum(group_prob[k]*rhos[k] for k in range(2));factorized=s['mu']*np.array([np.trace(marginal@op).real for op in ops])
  for a in (.5,1.,2.):
   energy=eta*V0*a**exponents*L;volume=V0*a**3;pressure=-exponents*energy/(3*volume)
   dv=volume*1e-5
   def total(vv):return np.sum(eta*V0*(vv/V0)**(exponents/3)*L)
   pnum=-(total(volume+dv)-total(volume-dv))/(2*dv)
   assert abs(pnum-pressure.sum())<1e-17
   rows.append({'epsilon':eps,'state':kind,'a':a,'joint_loads':L.tolist(),'factorized_marginal_loads':factorized.tolist(),'sector_energy_J':energy.tolist(),'sector_pressure_Pa':pressure.tolist(),'pressure_derivative_error_Pa':float(abs(pnum-pressure.sum()))})
  # Same joint conditional states under passive carrier permutation.
  perm=np.random.default_rng(5).permutation(N);after=np.array([np.trace(x[np.ix_(perm,perm)]@op[np.ix_(perm,perm)]).real for x,op in zip(sector_states,ops)])
  assert np.allclose(after,L,atol=1e-12,rtol=0)
 # Fixed-volume unitary generated by the same total positive H. This is a
 # dimensionless clock derivative; no extra SI time scale is fitted.
 Hs=[eta[j]*V0*s['mu'][j]*ops[j] for j in range(3)];H=sum(Hs);G=H/np.linalg.norm(H);drho=-1j*(G@packet-packet@G);rates=np.array([np.trace(drho@h).real for h in Hs]);assert abs(rates.sum())<1e-24
checks['positive_joint_conditional_states_and_loads']=True
checks['uniform_product_reproduces_existing_address_moments']=True
checks['joint_correlation_is_not_discarded']=any(np.max(np.abs(np.array(x['joint_loads'])-x['factorized_marginal_loads']))>1e-5 for x in rows if x['state']=='correlated')
checks['same_energy_supplies_pressure_derivative']=True
checks['passive_carrier_basis_change_preserves_load']=True
checks['same_energy_generator_conserves_fixed_volume_total']=True
checks['phenotype_operator_identity_preserves_budget']=all(abs(x['joint_loads'][0]-s['mu'][0])<1e-12 for x in rows)
checks['no_new_SI_coefficients_or_state_refits']=True
assert all(checks.values())
out={'status':'PASS','version':'0.1','checks':checks,'cases':rows,'operator_rule':'A_phi=I,A_D=Kc/2,A_R=Kb/2; load_s=sum_n w_n e_s(n) g_s(n) Tr[rho_n A_s]','energy_rule':'E_s=eta_s V0 a^n_s load_s; pressure_s=-n_s E_s/(3V)','scope':'positive classical-address conditional quantum-carrier map, fixed constitutive SI/load law','assumptions':['positive address response g_s','inherited operators and volume exponents','frozen SI coefficients','diagnostic address-carrier correlation; not measured cosmic state'],'not_derived':['SI conversion from pure arithmetic without calibrated anchors','unique physical load operators','full four-dimensional gravitational dynamics']}
(ROOT/'state_load_results.json').write_text(json.dumps(out,indent=2));print(json.dumps({'status':'PASS','checks':len(checks),'cases':len(rows)}))
